build:
    stage: build
    tags:
        - power
    script:
        - pwd
        - command -v make
        - command -v mbed
        - git submodule init
        - git submodule update
        - mbed deploy
        - bash source/NS-project/build.sh
