before_script:
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pwd
    # - git submodule update --init --recursive
    # - mbed deploy

build:
    stage: build
    tags:
        - power
    script:        
        - command -v make
        - command -v mbed
        # - bash source/NS-project/build.sh
