before_script:
    # - apt-get update
    # - apt-get --yes --force-yes install git ssh rsync
    - pwd
    - command -v make
    - command -v mbed
    - git submodule update --init --recursive
    - mbed deploy

build:
    stage: build
    tags:
        - power
    script:
        - bash source/NS-project/build.sh
