stages:
  - check-format
  - build
  - test
#   - check-format
#   - confluence
#   - deploy

variables:
    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - command -v make
    - command -v mbed

check-format:
    stage: check-format
    tags:
        - power
    script:
        - make -C source/NS-project format-check
    only:
        - master
        - develop
        - /(?i)release(?-i).*/

build:
    stage: build
    tags:
        - power
    script:        
        - make -C source/NS-project build
    only:
        - master
        - develop
        - /(?i)release(?-i).*/

test:
    stage: test
    tags:
        - power
    script:
        - make -C source/NS-project/test test
    only:
        - master
        - develop
        - /(?i)release(?-i).*/
