stages:
  - check-format
  - build
  - test
#   - check-format
#   - confluence
#   - deploy

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - command -v make
    - command -v mbed
    - chmod 755 ./source/NS-project/build.sh
    - chmod 755 ./source/NS-project/build_main.sh
    - chmod 755 ./source/NS-project/astyle.sh

check-format:
    stage: check-format
    tags:
        - power
    script:
        - make -C source/NS-project format-check
    only:
        - master
        - develop
        - /(?i)release(?-i).*/

build-power:
    stage: build
    tags:
        - power
    script:        
        - make -C source/NS-project power
    only:
        - master
        - develop
        - /(?i)release(?-i).*/

build-main:
    stage: build
    tags:
        - main
    script:        
        - make -C source/NS-project main
    only:
        - master
        - develop
        - /(?i)release(?-i).*/

test:
    stage: test
    tags:
        - power
    script:
        - make -C source/NS-project/test test
    only:
        - master
        - develop
        - /(?i)release(?-i).*/
