variables:
  SSH_PRIVATE_KEY: "HELLO WORLD"

before_script:
    # - apt-get update
    # - apt-get --yes --force-yes install git ssh rsync
    - pwd
    - command -v make
    - command -v mbed
    # - mkdir "${HOME}/.ssh"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    # - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    # - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
    # - chmod 700 "${HOME}/.ssh/id_rsa"
    # - git submodule update --init --recursive
    # - mbed deploy

build:
    stage: build
    tags:
        - power
    script:
        # - bash source/NS-project/build.sh
