build:
    stage: build
    tags:
        - power
    script:
        - pwd
        - command -v make
        - command -v mbed
        - command -v mbed-cli
        # - bash source/NS-project/build.sh
